apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backuprolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: backupserviceacc
  namespace: default
roleRef:
  kind: Role
  name: pod-list-exec
  apiGroup: rbac.authorization.k8s.io